steps:
- script: |
    npm install --force
    sudo chmod u+x node_modules/@azure-tools/azcopy-darwin/dist/bin/azcopy_darwin_amd64 \
      node_modules/@azure-tools/azcopy-linux/dist/bin/azcopy_linux_amd64

- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: ci

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
