steps:
- script: |
    npm install --force @azure-tools/azcopy-darwin \
      @azure-tools/azcopy-linux \
      @azure-tools/azcopy-win32 \
      @azure-tools/azcopy-win64
    sudo chmod u+x node_modules/@azure-tools/azcopy-darwin/dist/bin/azcopy_darwin_amd64 \
      node_modules/@azure-tools/azcopy-linux/dist/bin/azcopy_linux_amd64

- task: Npm@1
  displayName: 'cleanReadme'
  inputs:
    command: custom
    customCommand: run cleanReadme

- task: Npm@1
  displayName: 'Package'
  inputs:
    command: custom
    customCommand: run package

- task: CopyFiles@2
  displayName: 'Copy vsix to staging directory'
  inputs:
    Contents: '**/*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: vsix
  condition: ne(variables['System.PullRequest.IsFork'], 'True')
