name: Node PR Lint, Build and Test

on:
  # Trigger when manually run
  workflow_dispatch:

  # Trigger on pushes to `main` or `rel/*`
  push:
    branches:
      - main
      - rel/*

  # Trigger on pull requests to `main` or `rel/*`
  pull_request:
    branches:
      - main
      - rel/*

# not using shared template (https://github.com/microsoft/vscode-azuretools/tree/main/.github/workflows) so that we can install azcopy
jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "."

    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci --no-optional

      # Install AzCopy
      - run: npm install --force @azure-tools/azcopy-darwin @azure-tools/azcopy-linux @azure-tools/azcopy-win32 @azure-tools/azcopy-win64
      - run: npm run setazcopypermissions

      # Set AzCopy permissions
      # comment out in main because I think it is effecting other branches
      # - run: npm run postinstall

      # Lint
      - run: npm run lint

      # Build
      - run: npm run build

      # Package
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            **/*.vsix
            **/*.tgz
            !**/node_modules

      # Test
      - run: xvfb-run -a npm test
