name: Node PR Lint, Build and Test

on:
  # Trigger when manually run
  workflow_dispatch:

  # Trigger on pushes to `main` or `rel/*`
  push:
    branches:
      - main
      - rel/*

  # Trigger on pull requests to `main` or `rel/*`
  pull_request:
    branches:
      - main
      - rel/*

# not using shared template (https://github.com/microsoft/vscode-azuretools/tree/main/.github/workflows) so that we can install azcopy
jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "."

    steps:
      # Setup
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Using Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: .nvmrc
      - run: npm ci --no-optional

      # Install AzCopy
      - run: npm install --force @azure-tools/azcopy-darwin @azure-tools/azcopy-linux @azure-tools/azcopy-win32 @azure-tools/azcopy-win64

      # Lint
      - run: npm run lint

      # Build
      - run: npm run build

      # Package
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Artifacts
          path: |
            **/*.vsix
            **/*.tgz
            !**/node_modules

      # Test
      - run: xvfb-run -a npm test
